<a href="https://colab.research.google.com/github/NeeluDevi/assignment1/blob/main/07_Mar_AssQ_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Q1. What are the three measures of central tendency?**

1. Mean()
2. median()
3. mode()

**Q2. What is the difference between the mean, median, and mode? How are they used to measure the
central tendency of a dataset?**

**mean()-** it is the average of all elements.
**formula :**sum of all elements/size of elements

**median -** The median is the middle value when a data set is ordered from least to greatest .
**Formula: if count=even then median=sum of 2 middle elements/2
if count=odd then median=midlle element**

**mode()-**The mode is the number that occurs most often in a data set.

In [ ]:
import seaborn as sns


In [ ]:
df=sns.load_dataset('tips')

In [ ]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df['total_bill'].mean()

19.78594262295082

In [ ]:
df['total_bill'].median()

17.795

In [ ]:
df['total_bill'].mode()

0    13.42
Name: total_bill, dtype: float64

**Q3. Measure the three measures of central tendency for the given height data:
[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]**

In [ ]:
data=[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]

In [ ]:
import numpy as np
import statistics as stat
import pandas as pd
ndata=np.array(data)

In [ ]:
ndata

array([178. , 177. , 176. , 177. , 178.2, 178. , 175. , 179. , 180. ,
       175. , 178.9, 176.2, 177. , 172.5, 178. , 176.5])

In [ ]:
np.mean(ndata)

177.01875

In [ ]:
np.median(ndata)

177.0

In [ ]:
stat.mode(ndata)

178.0

**Q4. Find the standard deviation for the given data:
[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]**

In [ ]:
data=[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]

In [ ]:
data=np.array(data)

In [ ]:
data

array([178. , 177. , 176. , 177. , 178.2, 178. , 175. , 179. , 180. ,
       175. , 178.9, 176.2, 177. , 172.5, 178. , 176.5])

In [ ]:
data.std()

1.7885814036548633

**Q5. How are measures of dispersion such as range, variance, and standard deviation used to describe
the spread of a dataset? Provide an example.**

**range :-**The range is the easiest dispersion of data or measure of variability.To calculate the range, prepare all the values in ascending order, then subtract the lowest value from the highest value.**Range = Highest_value  – Lowest_value** 

**variance :-**Variance is a simple measure of dispersion. Variance measures how far each number in the dataset from the mean.

**standard deviation :-**Standard deviation is a squared root of the variance to get original values. Low standard deviation indicates data points close to mean.

In [ ]:
# let's consider a dataset of the ages of 10 students in a class: 20, 21, 22, 23, 24, 25, 26, 27, 28, 29.

data=np.array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
data

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
#calculate range
range=np.max(data)-np.min(data)
print("range:",range)

range: 9


In [ ]:
#calculate variance
mean=np.mean(data)
variance=np.mean((data-mean)**2)
print("variance:",variance)

variance: 8.25


In [ ]:
np.std(data)

2.8722813232690143

In [ ]:
#calculate standard deviation

std=np.sqrt(variance)
print("Standard deviation :",std)

Standard deviation : 2.8722813232690143


**Q6. What is a Venn diagram?**

**Venn diagram :-**A Venn diagram is a widely used diagram style that shows the logical relation between sets.

**Q7. For the two given sets A = (2,3,4,5,6,7) & B = (0,2,6,8,10). Find:
(i) A B
(ii) A ⋃ B**

In [ ]:
 A = set((2,3,4,5,6,7))
 B = set((0,2,6,8,10))

 #intersection 
 inter=A.intersection(B)
 print("Intersection of A and B :",inter)


Intersection of A and B : {2, 6}


In [ ]:
#Union
un=A.union(B)
print("Union of A and B :",un)

Union of A and B : {0, 2, 3, 4, 5, 6, 7, 8, 10}


**Q8. What do you understand about skewness in data?**

**Ans :-**Skewness is a measure of the lack of symmetry in a distribution.In a symmetric distribution, the mean, median, and mode are all equal.

**Q9. If a data is right skewed then what will be the position of median with respect to mean?**

**Ans :-**If the data is right skewed then the position of median is less than the mean.    
**mean>median>mode**

**Q10. Explain the difference between covariance and correlation. How are these measures used in
statistical analysis?**

**Ans :-**

1.   Covariance measures how two variables change together, while correlation measures the strength and direction of the linear relationship between two variables.
2.  Covariance is affected by the scale of the variables, while correlation is not.
3.  Covariance can take on any value, while correlation ranges from -1 to 1




**Q11. What is the formula for calculating the sample mean? Provide an example calculation for a
dataset.**

**Ans :-**                        
**formula for sample mean :-** x̄ = ( Σ xi ) ÷ n

(
x
1
+
x
2
+
x
3
+
⋯
+
x
n
)/
n


**Q12. For a normal distribution data what is the relationship between its measure of central tendency?**

**Ans :-** Any normal distribution has a graph that is perfectly symmetric about a vertical line through its peak.Therefore, all measure central tendency are same.

mean=mode=median

**Q13. How is covariance different from correlation?**

**Ans :-**Covariance shows you how the two variables differ, whereas correlation shows you how the two variables are related.

**Q14. How do outliers affect measures of central tendency and dispersion? Provide an example.**

In [ ]:
data = np.array([1, 2, 3, 4, 5, 100])

# Calculate the mean and median
mean = np.mean(data)
median = np.median(data)
print("Mean :",mean)
print("Median :",median)

Mean : 19.166666666666668
Median : 3.5


In [ ]:
#Calculate the variance and standard deviation
variance = np.var(data)
std_dev = np.std(data)
print("Variance :",variance)
print("Standard deviation :",std_dev)

Variance : 1308.4722222222222
Standard deviation : 36.17281053805775
